################################################################
#
# PlayStation 2 build: ps2/DOOM.ELF, with raylib4PlayStation2.
# Needs the ps2dev toolchain and the libraries from
# ../packaging/ps2/build-deps.sh; ../packaging/ps2/build.sh does
# both. See ../packaging/ps2/README.txt.
#
#	make -f Makefile.ps2
#

ifeq ($(PS2SDK),)
$(error PS2SDK is not set; see ../packaging/ps2/README.txt)
endif

EE_TOOL_PREFIX ?= mips64r5900el-ps2-elf-
CC=	$(EE_TOOL_PREFIX)gcc
CXX=	$(EE_TOOL_PREFIX)g++
BIN2C=	$(PS2SDK)/bin/bin2c

CFLAGS=-D_EE -G0 -O2 -std=gnu11 -fwrapv -fno-strict-aliasing -Wall \
	-DNORMALUNIX -DPLATFORM_PLAYSTATION2 \
	-I$(PS2SDK)/ports/include -I$(PS2SDK)/ee/include \
	-I$(PS2SDK)/common/include -I$(O)
LDFLAGS=-T$(PS2SDK)/ee/startup/linkfile -O2 \
	-L$(PS2SDK)/ee/lib -L$(PS2SDK)/ports/lib -Wl,-zmax-page-size=128
# raylib4PlayStation2's own set, then the IOP module loading
# (-lpatches), USB storage (-lfileXio) and the CD drive (-lcdvd).
LIBS=-lraylib -lps2gl -lps2stuff -lpad -ldma \
	-lfileXio -lpatches -lcdvd -lm

# subdirectory for objects
O=ps2

# IOP modules built into the ELF, for mass: (USB storage).
IRX=	iomanX fileXio usbd bdm bdmfs_fatfs usbmass_bd

# The same objects as the Linux Makefile, and i_ps2.o.
OBJS=				\
		$(O)/doomdef.o		\
		$(O)/doomstat.o		\
		$(O)/dstrings.o		\
		$(O)/i_system.o		\
		$(O)/i_sound.o		\
		$(O)/i_music.o		\
		$(O)/opl3.o		\
		$(O)/i_video.o		\
		$(O)/i_raylib.o		\
		$(O)/i_ps2.o		\
		$(O)/i_net.o			\
		$(O)/tables.o			\
		$(O)/f_finale.o		\
		$(O)/f_wipe.o 		\
		$(O)/d_main.o			\
		$(O)/d_net.o			\
		$(O)/d_items.o		\
		$(O)/g_game.o			\
		$(O)/m_menu.o			\
		$(O)/m_misc.o			\
		$(O)/m_argv.o  		\
		$(O)/m_bbox.o			\
		$(O)/m_fixed.o		\
		$(O)/m_swap.o			\
		$(O)/m_cheat.o		\
		$(O)/m_random.o		\
		$(O)/am_map.o			\
		$(O)/p_ceilng.o		\
		$(O)/p_doors.o		\
		$(O)/p_enemy.o		\
		$(O)/p_floor.o		\
		$(O)/p_inter.o		\
		$(O)/p_lights.o		\
		$(O)/p_map.o			\
		$(O)/p_maputl.o		\
		$(O)/p_plats.o		\
		$(O)/p_pspr.o			\
		$(O)/p_setup.o		\
		$(O)/p_sight.o		\
		$(O)/p_spec.o			\
		$(O)/p_switch.o		\
		$(O)/p_mobj.o			\
		$(O)/p_telept.o		\
		$(O)/p_tick.o			\
		$(O)/p_saveg.o		\
		$(O)/p_user.o			\
		$(O)/r_bsp.o			\
		$(O)/r_data.o			\
		$(O)/r_draw.o			\
		$(O)/r_main.o			\
		$(O)/r_plane.o		\
		$(O)/r_segs.o			\
		$(O)/r_sky.o			\
		$(O)/r_things.o		\
		$(O)/w_wad.o			\
		$(O)/wi_stuff.o		\
		$(O)/u_mapinfo.o		\
		$(O)/v_video.o		\
		$(O)/st_lib.o			\
		$(O)/st_stuff.o		\
		$(O)/hu_stuff.o		\
		$(O)/hu_lib.o			\
		$(O)/s_sound.o		\
		$(O)/z_zone.o			\
		$(O)/info.o				\
		$(O)/sounds.o

IRXOBJS=	$(IRX:%=$(O)/%_irx.o)

all:	 $(O)/DOOM.ELF

clean:
	rm -rf $(O)

# Linked by g++: raylib and ps2gl are C++.
$(O)/DOOM.ELF:	$(OBJS) $(IRXOBJS) $(O)/i_main.o
	$(CXX) $(LDFLAGS) $(OBJS) $(IRXOBJS) $(O)/i_main.o \
	-o $(O)/DOOM.ELF $(LIBS)

$(O)/%.o:	%.c
	@mkdir -p $(O)
	$(CC) $(CFLAGS) -c $< -o $@

# Each module as a C array, <name>_irx[] and size_<name>_irx.
$(O)/%_irx.c:	$(PS2SDK)/iop/irx/%.irx
	@mkdir -p $(O)
	$(BIN2C) $< $@ $*_irx

$(O)/%_irx.o:	$(O)/%_irx.c
	$(CC) $(CFLAGS) -c $< -o $@

.PRECIOUS:	$(O)/%_irx.c

#############################################################
#
#############################################################
